databases:
  - name: credit_smart
    databaseName: credit_smart_mdih
    user: ccredit_smart_mdih_user
    plan: free

services:
  - type: web
    name: credit_smart # the name of this service, eg hello-world
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - KEY: DATABASE_URL
        fromDatabase:
          name: credit_smart_mdih
          property: connectionString
      - key: RAILS_MASTER_KEY 
        sync: false
